POST http://localhost:3000/register/
Content-Type:application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwNTM3Mjk3fQ.PqydFFTN-e_q9XXjnpR3VqMElNmRNG0BnvNpnGetsQI
{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}


POST http://localhost:3000/login/
Content-Type:application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwNTM3Mjk3fQ.PqydFFTN-e_q9XXjnpR3VqMElNmRNG0BnvNpnGetsQI

{
  "username":"JoeBiden",
  "password":"biden@123"
}

GET  http://localhost:3000/user/tweets/feed/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwNTM3Mjk3fQ.PqydFFTN-e_q9XXjnpR3VqMElNmRNG0BnvNpnGetsQI


GET  http://localhost:3000/user/following/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwNTM3Mjk3fQ.PqydFFTN-e_q9XXjnpR3VqMElNmRNG0BnvNpnGetsQI




GET  http://localhost:3000/user/followers/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwNTM3Mjk3fQ.PqydFFTN-e_q9XXjnpR3VqMElNmRNG0BnvNpnGetsQI

GET  http://localhost:3000/tweets/:tweetId/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwNTM3Mjk3fQ.PqydFFTN-e_q9XXjnpR3VqMElNmRNG0BnvNpnGetsQI

GET  http://localhost:3000/tweets/:tweetId/likes/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwNTM3Mjk3fQ.PqydFFTN-e_q9XXjnpR3VqMElNmRNG0BnvNpnGetsQI

GET  http://localhost:3000/tweets/:tweetId/replies/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwNTM3Mjk3fQ.PqydFFTN-e_q9XXjnpR3VqMElNmRNG0BnvNpnGetsQI

GET  http://localhost:3000/user/tweets
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwNTM3Mjk3fQ.PqydFFTN-e_q9XXjnpR3VqMElNmRNG0BnvNpnGetsQI

GET  http://localhost:3000/user/tweets
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwNTM3Mjk3fQ.PqydFFTN-e_q9XXjnpR3VqMElNmRNG0BnvNpnGetsQI






DELETE http://localhost:3000/tweets/:tweetId/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwNTM3Mjk3fQ.PqydFFTN-e_q9XXjnpR3VqMElNmRNG0BnvNpnGetsQI
